/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador_.lester_monterroso;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
/**
 *
 * @author Lester Monterroso
 */
public class Abrirtexto extends javax.swing.JFrame {
    FileReader fr1 = null;
        BufferedReader bf1 = null;
        File archivos = null;
    PrintWriter pw = null;
    
    
     FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos imm","imm");
     public static String lexico1="";
public static int lineas=1;
String imprimelinea;
 JFileChooser n= new JFileChooser();
 JFileChooser fc = new JFileChooser();
    JFileChooser seleccionado= new JFileChooser();
    File archivo;
     FileInputStream archivoentrada;
        String lectura="";
         String path;
          File f;
           File jj;
/**
     * Creates new form Abrirtexto
     */

 public Abrirtexto() {
        initComponents();

  this.setIconImage( new ImageIcon(getClass().getResource("/iconos/icon.png")).getImage()); //icono de formulario
         this.setLocationRelativeTo(null);//formulario al centro
         this.setResizable(false);//no puede cambiar tamaño
        
    }
   


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtabrir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abrir Archivo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 2, 14)); // NOI18N
        jLabel1.setText("Seleccione el Archivo");

        jButton1.setText("Examinar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtabrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  // TODO add your handling code here:
   File miDir = new File (".");
   String midir2="";
   try {
      midir2=miDir.getCanonicalPath();
      
       }
     catch(Exception e) {
     
       }
   
   
   
     String ruta;
     File borrar = new File(midir2+"/archivos/ruta.txt");
    try{
     borrar.delete();
    }catch(Exception e){}
     
     
      String ruta2;
     File borrar2 = new File(midir2+"/archivos/nombre.txt");
     
     try{
     borrar2.delete();
     }catch(Exception e){
     
     }
     
     
     
       fc.setFileFilter(filtro);
        int respuesta = fc.showOpenDialog(this);
      
        if (respuesta == JFileChooser.APPROVE_OPTION) {
         jj=fc.getSelectedFile();
            
             if(jj.canRead()){
                if(jj.getName().endsWith("imm")){
               
                txtabrir.setText(fc.getSelectedFile().toString());
                ruta=txtabrir.getText();
                ruta2=jj.getName();
          try(FileWriter fw = new FileWriter(midir2+"/archivos/ruta.txt", true);
    BufferedWriter bw = new BufferedWriter(fw);
    PrintWriter out = new PrintWriter(bw))
    {
        out.println(ruta);
        //more code
       
        //more code
} catch (IOException e) {
      JOptionPane.showMessageDialog(null, "Error en obtencion de ruta para compilación","Error de Lectura", JOptionPane.ERROR_MESSAGE);
    //exception handling left as an exercise for the reader
}
                   try(FileWriter nombre = new FileWriter(midir2+"/archivos/nombre.txt", true);
    BufferedWriter nombre1 = new BufferedWriter(nombre);
    PrintWriter out1 = new PrintWriter(nombre1))
    {
        out1.println(ruta2);
        //more code
       
        //more code
} catch (IOException e) {
      JOptionPane.showMessageDialog(null, "Error en obtencion de ruta para compilación","Error de Lectura", JOptionPane.ERROR_MESSAGE);
    //exception handling left as an exercise for the reader
} 
                
                
                
                
                
                
                }else{
                    JOptionPane.showMessageDialog(null, "Seleccione un archivo con extención imm","Error de Lectura", JOptionPane.ERROR_MESSAGE);
                }  
            }
            
            
            
            
            
           
            }else{
         JOptionPane.showMessageDialog(this, "Seleccione una ruta");
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        try{
            path=txtabrir.getText();
        f = new File(path);
         try{

            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String aux;
   
      aux = br.readLine();
      
       Interfaz_compilador.txtlineas1.setText("");
                Interfaz_compilador.txtlineas1.setText("1");
      
        while(aux!=null){

               lectura = lectura+aux+"\n";
             
               
               
               
               
               lineas=lineas+1;
               imprimelinea = ("\n"+(Integer.toString(lineas)));
               Interfaz_compilador.txtlineas1.append(imprimelinea);
       aux = br.readLine();
        }
        Interfaz_compilador.txtarchivo1.setText(null);
       Interfaz_compilador.txtarchivo1.append(lectura);
   
       
       br.close();
       fr.close();
          } catch(IOException e){ JOptionPane.showMessageDialog(this, "Error al cargar el archivo");}
        
       
         this.dispose();
        
        }catch(Exception e){ 
            
            JOptionPane.showMessageDialog(this, "Error al cargar el archivo");}
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Abrirtexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Abrirtexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Abrirtexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Abrirtexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Abrirtexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtabrir;
    // End of variables declaration//GEN-END:variables
}
