/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package compilador_.lester_monterroso;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Lester Monterroso
 */
public class Interfaz_compilador extends javax.swing.JFrame {
    public static  int numero=1;
    private Set<Integer> pressed = new HashSet<Integer>(); 
String imprimelineas;
File nuevo;
FileOutputStream guardar;
JFileChooser ruta= new JFileChooser();
int lineas_menos;
    /** Creates new form Interfaz_compilador */
    public Interfaz_compilador() {
       
        initComponents();
       paneltabla.setVisible(false);
        lbltabla.setVisible(false);
this.setExtendedState(MAXIMIZED_BOTH);
 
  this.setIconImage( new ImageIcon(getClass().getResource("/iconos/icono.png")).getImage()); 
         
        
        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarchivo1 = new javax.swing.JTextArea();
        txtlineas1 = new javax.swing.JTextArea();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lbltabla = new javax.swing.JLabel();
        paneltabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Compilar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menutabla = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador JD Lester Monterroso");
        setBackground(new java.awt.Color(204, 255, 153));
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane5.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane5.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        txtarchivo1.setColumns(20);
        txtarchivo1.setRows(5);
        txtarchivo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtarchivo1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtarchivo1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtarchivo1);

        txtlineas1.setEditable(false);
        txtlineas1.setBackground(new java.awt.Color(204, 204, 204));
        txtlineas1.setColumns(2);
        txtlineas1.setLineWrap(true);
        txtlineas1.setRows(2);
        txtlineas1.setTabSize(2);
        txtlineas1.setText("1");
        txtlineas1.setAutoscrolls(false);
        txtlineas1.setCaretColor(new java.awt.Color(51, 51, 255));
        txtlineas1.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtlineas1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(txtlineas1)))
        );

        jScrollPane5.setViewportView(jPanel2);

        lbltabla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltabla.setForeground(new java.awt.Color(255, 255, 102));
        lbltabla.setText("Tabla de Tokens Final");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"         1", "        ID", null},
                {"         2", "      Entero", null},
                {"         3", "       Real", null},
                {"         4", "     Cadena", null},
                {"         5", "     Op. más", null},
                {"         6", "   Op. menos", null},
                {"         7", " Op. multipicar", null},
                {"         8", "   Op. dividir", null},
                {"         9", " Op. potencia", null},
                {"        10", "   p. abierto", null},
                {"        11", "   p.cerrado", null},
                {"        12", "  llave.abierta", null},
                {"        13", "  llave.cerrada", null},
                {"        14", "     S.igual", null},
                {"        15", "    S.mayor", null},
                {"        16", "    S.menor", null},
                {"        17", " fin.sentencia", null},
                {"        18", "   dos.puntos", null},
                {"        19", "      s.coma", null},
                {"      100", "pr.procedimiento", null},
                {"      101", "   pr.imprimir", null},
                {"      102", "     pr.leer", null},
                {"      103", "   pr.cadena", null},
                {"      104", "    pr.entero", null},
                {"      105", "     pr.real", null},
                {"      106", "      f.si", null},
                {"      107", "      fsino", null},
                {"      108", "     fin.si", null},
                {"      109", "  pr.principal", null},
                {"      110", "  f.entonces", null},
                {"      111", "  pr.metodo", null}
            },
            new String [] {
                "Numero Token", "Numbre", "Cantidad "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla1.setRowHeight(20);
        jScrollPane1.setViewportView(tabla1);

        javax.swing.GroupLayout paneltablaLayout = new javax.swing.GroupLayout(paneltabla);
        paneltabla.setLayout(paneltablaLayout);
        paneltablaLayout.setHorizontalGroup(
            paneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        paneltablaLayout.setVerticalGroup(
            paneltablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/logoumg2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbltabla))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paneltabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbltabla)
                .addGap(59, 59, 59)
                .addComponent(paneltabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/Openfolderorange_9651 (1).png"))); // NOI18N
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/diskette_save_saveas_1514.png"))); // NOI18N
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/action_exit_close_remove_13915 (1).png"))); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analisis");

        Compilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/1486486316-arrow-film-movie-play-player-start-video_81236.png"))); // NOI18N
        Compilar.setText("Compilar");
        Compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompilarActionPerformed(evt);
            }
        });
        jMenu2.add(Compilar);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/processor_103541.png"))); // NOI18N
        jMenu3.setText("Analizar Archivo");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/file_text_14812 (1).png"))); // NOI18N
        jMenuItem4.setText("Salida del Programa");
        jMenu3.add(jMenuItem4);

        menutabla.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menutabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/spreadsheet_table_document_page_5852.png"))); // NOI18N
        menutabla.setText("Tabla de Símbolos");
        menutabla.setEnabled(false);
        menutabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutablaActionPerformed(evt);
            }
        });
        jMenu3.add(menutabla);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador_/lester_monterroso/error_warning_6226.png"))); // NOI18N
        jMenuItem6.setText("Mostrar el Archivo de Errores");
        jMenu3.add(jMenuItem6);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         Abrirtexto abrir=new Abrirtexto();
        abrir.show();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu1ActionPerformed
 public String GuardarATexto(File nuevo,String contenido){
        String respuesta=null;
        try{
            guardar = new FileOutputStream(nuevo);
            byte[] bytesTxt=contenido.getBytes();
            guardar.write(bytesTxt);
            respuesta="Archivo guardado con Exito";
        }catch (Exception e){
            
        }
        return respuesta;
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed


 if (ruta.showDialog(null, "Guardar Archivo")==JFileChooser.APPROVE_OPTION) {
            nuevo=ruta.getSelectedFile();
            if(nuevo.getName().endsWith("imm")){
                String contenido =txtarchivo1.getText();
                String respuesta=GuardarATexto(nuevo,contenido);
                if(respuesta!=null){
                    JOptionPane.showMessageDialog(null, respuesta,"Guardar", JOptionPane.INFORMATION_MESSAGE);
                    txtarchivo1.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar archivo","Error al Guardar", JOptionPane.ERROR_MESSAGE);
                }
                        }else{
                 JOptionPane.showMessageDialog(null, "El archivo debe guardarse con extención .imm","Error al Guardar", JOptionPane.ERROR_MESSAGE);
            }
        }















        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompilarActionPerformed

        menutabla.setEnabled(true);
       Lexico analisis = new Lexico();
       analisis.inicio();



        // TODO add your handling code here:
    }//GEN-LAST:event_CompilarActionPerformed

    private void txtarchivo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtarchivo1KeyReleased

        if(evt.isControlDown() || evt.getKeyCode()==10 || evt.getKeyCode()==8 || evt.getKeyCode()==127){
            contarlineas();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtarchivo1KeyReleased

    private void txtarchivo1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtarchivo1KeyPressed

      

        // TODO add your handling code here:
    }//GEN-LAST:event_txtarchivo1KeyPressed

    private void menutablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutablaActionPerformed
 
           String[] numero = new String [35];
        FileReader miruta=null;
   BufferedReader ruta1 = null;
    File ruta2 = null;
     int fila=0;
       
        String valor;
         try{
        ruta2= new File("total.txt");
        miruta = new FileReader(ruta2);
            ruta1 = new BufferedReader(miruta);
           String a;
            while ((a=ruta1.readLine())!=null){
                numero[fila]=a;
                fila++;
      
              
       miruta.close();
            }
        
        }catch (Exception ex){} 
        
        
        
        
        
        
        
        paneltabla.setVisible(true);
lbltabla.setVisible(true);
for (int i=0;i<31;i++){
tabla1.setValueAt(numero[i], i, 2);
}


        // TODO add your handling code here:
    }//GEN-LAST:event_menutablaActionPerformed
 public void contarlineas(){
        int totalrows=txtarchivo1.getLineCount();
            txtlineas1.setText("1\n");
            for(int i=2; i<=totalrows;i++){
                txtlineas1.setText(txtlineas1.getText()+i+"\n");
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_compilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_compilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Compilar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbltabla;
    private javax.swing.JMenuItem menutabla;
    public javax.swing.JPanel paneltabla;
    public static javax.swing.JTable tabla1;
    public static javax.swing.JTextArea txtarchivo1;
    public static javax.swing.JTextArea txtlineas1;
    // End of variables declaration//GEN-END:variables

}









